### ISSUE TITLE
error: unknown type name ‘php_socket’

### ISSUE THREAD

**Issue by xiaobopang** [youzan/zan#15]
在编译zan extension  的时候，执行到make这一步的时候出现下面的错误。排查了sockets和openssl都有正确安装。求解答下面大概是什么情况下会造成这种错误。
In file included from /root/temp/zan/zan-extension/swoole.c:20:0:
/root/temp/zan/zan-extension/php_swoole.h:452:1: error: unknown type name ‘php_socket’
 php_socket *swoole_convert_to_socket(int sock);
 ^
Makefile:194: recipe for target 'swoole.lo' failed
make: *** [swoole.lo] Error 1

**Comment by bcdevhz** [comment]
还是sockets扩展在你非编译安装环境漏宏定义了,你拉下最新代码

**Comment by zxcvdavid** [comment]
@peterpang55 怎么样 问题解决了吗？

**Comment by bcdevhz** [comment]
fixed at commit:
https://github.com/youzan/zan/commit/c9883baf8c0a39017aba335aba2f7a80a5d61b81 
and https://github.com/youzan/zan/commit/4236867d235c65122a5228dc42442b4e79a70e0c
