### ISSUE TITLE
当某个worker进程处理了maxRquest个http请求后平滑reload的问题

### ISSUE THREAD

**Issue by gouchaoer** [youzan/zan#16]
我们知道swoole/zan有个参数可以控制当http请求次数达到某个值之后，重启该worker以防止内存泄露

今天参加了swoole的线下交流发现这个问题挺严重的，有的厂不敢设置这个maxRequest，因为在协程中达到了maxRequest立即重启的话可能有的

**Comment by gouchaoer** [comment]
协程还没有处理完http请求，强制重启就会导致请求失败。。。。而且由于tcp池分别属于不同的worker，所以该worker的tcp池也会被回收吧。。。

由于php的垃圾回收是引用计数魔改的，常驻内存的话很多时候会遇到内存泄露问题，很难排查，不知道有赞怎么处理这个问题的。。。。zan能够像nginx那样，达到maxRequest的时候把分配给该worker的请求停掉，等该worker的请求都处理完了再重启改worker么？

**Comment by gouchaoer** [comment]
很多php的库或者框架都php-fpm中来的，不用考虑内存问题，现在用到常驻内存的php-cli上内存泄露情况太普遍了，而swoole/zan和jvm不同的地方在于zan开了n个彼此独立的worker进程，而jvm是同一个进程，我就想既然php的垃圾回收很难做好，而worker进程反正都是独立的，还不如把平滑重启做了

**Comment by gouchaoer** [comment]
https://wiki.swoole.com/wiki/page/300.html

**Comment by zxcvdavid** [comment]
@gouchaoer 你好，我们目前的maxRequest是在zanPHP层面实现的，https://github.com/youzan/zanphp/blob/453a091f0bee8e706621938fa5ce39892ea4c7f4/src/Network/Server/Monitor/Worker.php

我们接下来有计划在zan中实现更好的解决方案，敬请期待。
