### ISSUE TITLE
真正有开源精神就应该反哺于swoole，而不是为了kdi创造一个僵尸项目

### ISSUE THREAD

**Issue by pavlelee** [youzan/zan#2]

**Comment by zxcvdavid** [comment]
：） 道德绑架在这儿没用

**Comment by Liv1020** [comment]
我感觉到了你教育的缺失

**Comment by xiezhenye** [comment]
kdi是啥

**Comment by wilon** [comment]
为了赚钱脸都不要了
![default](https://user-images.githubusercontent.com/7512755/27504722-3a510f48-58c2-11e7-9ac1-e739e055bda1.png)
