### ISSUE TITLE
Bug 反馈，i 应该改成 index，见截图。

### ISSUE THREAD

**Issue by springleng** [youzan/zan#4]
<img width="641" alt="zan_bug" src="https://user-images.githubusercontent.com/1900972/27493060-f8683fa8-587a-11e7-81f0-a994da7afe83.png">

**Comment by springleng** [comment]
还有下图的问题可能与#ifndef HAVE_DAEMON 系统环境检测判断有关系，我的机器是macos最新版本。
<img width="1247" alt="daemon_function" src="https://user-images.githubusercontent.com/1900972/27493322-06230d84-587c-11e7-8367-fa17666ec16d.png">

**Comment by bcdevhz** [comment]
开启ring_buffer功能的编译问题已fix。
mac 环境下宏HAVE_DAEMON默认开启，在macos 10.5下的系统调用daemon被废弃。因此被clang编译报waring,不影响使用。
多谢反馈。

**Comment by springleng** [comment]
@chuchenxihyl @zxcvdavid 看看这个，网上搜到的解决办法，不知道有没有用。PR #14 中我在config.m4中修改了CFLAGS，加了参数-Wno-deprecated-declarations 屏蔽了warning信息。

```c
#if __APPLE__
// In Mac OS X 10.5 and later trying to use the daemon function gives a “‘daemon’ is deprecated”
// error, which prevents compilation because we build with "-Werror".
// Since this is supposed to be portable cross-platform code, we don't care that daemon is
// deprecated on Mac OS X 10.5, so we use this preprocessor trick to eliminate the error message.
#define daemon yes_we_know_that_daemon_is_deprecated_in_os_x_10_5_thankyou
#endif

#if __APPLE__
#undef daemon
extern int daemon(int, int);
#endif
```

**Comment by bcdevhz** [comment]
OK，clang加编译选项-Wno-deprecated-declarations

**Comment by springleng** [comment]
@chuchenxihyl 现在这么解决https://github.com/youzan/zan/pull/14/commits/af71b646cfe6e9eefaad33a2949349552bdba615 貌似也可以，不用屏蔽warning。
