### ISSUE TITLE
macos 10.11.6 PHP Warning:  PHP Startup: Unable to load dynamic library

### ISSUE THREAD

**Issue by nbzx** [youzan/zan#47]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.6_18/lib/php/extensions/no-debug-non-zts-20160303/zan.so' - dlopen(/usr/local/Cellar/php71/7.1.6_18/lib/php/extensions/no-debug-non-zts-20160303/zan.so, 9): Symbol not found: _program_invocation_name
  Referenced from: /usr/local/Cellar/php71/7.1.6_18/lib/php/extensions/no-debug-non-zts-20160303/zan.so
  Expected in: flat namespace
 in /usr/local/Cellar/php71/7.1.6_18/lib/php/extensions/no-debug-non-zts-20160303/zan.so in Unknown on line 0

--------------
gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by imaben** [comment]
fixed
