### ISSUE TITLE
执行make，报错

### ISSUE THREAD

**Issue by xiyang2011** [youzan/zan#5]
ubuntu 14.04lts
lnmp一键安装包1.3正式版本 php5.4
在执行make，报如下错误
/usr/bin/ld: skipping incompatible /usr/zan/lib/libhiredis_linux.a when searching for -lhiredis_linux
/usr/bin/ld: cannot find -lhiredis_linux
collect2: error: ld returned 1 exit status
make: *** [zan.la] 错误 1

**Comment by xhjcehust** [comment]
php版本5.6及以上哦，推荐使用php7

**Comment by xiyang2011** [comment]
已经使用测试过5.6、7.0.7等php版本，依然存在这个问题
/bin/bash /usr/zan/zan-extension/libtool --mode=link cc -DPHP_ATOM_INC -I/usr/zan/zan-extension/include -I/usr/zan/zan-extension/main -I/usr/zan/zan-extension -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/zan/zan-extension/include  -DHAVE_CONFIG_H  -std=gnu99 -Wall -pthread -g -O2 -fbounds-check -fstack-check -fstack-protector -fstack-protector-all -fno-strict-aliasing  -lpthread -o zan.la -export-dynamic -avoid-version -prefer-pic -module -rpath /usr/zan/zan-extension/modules  swoole.lo swoole_server.lo swoole_server_port.lo swoole_connpool.lo swoole_client.lo swoole_event.lo swoole_timer.lo swoole_async.lo swoole_process.lo swoole_buffer.lo swoole_http_server.lo swoole_http_v2_server.lo swoole_websocket_server.lo swoole_http_client.lo swoole_mysql.lo swoole_redis.lo swoole_nova.lo src/Base.lo src/core/hashmap.lo src/core/RingQueue.lo src/core/string.lo src/core/array.lo src/core/list.lo src/core/heap.lo src/core/log.lo src/core/rbtree.lo src/memory/ShareMemory.lo src/memory/MemoryGlobal.lo src/memory/RingBuffer.lo src/memory/FixedPool.lo src/memory/Malloc.lo src/memory/Table.lo src/memory/Buffer.lo src/factory/Factory.lo src/factory/FactoryThread.lo src/factory/FactoryProcess.lo src/factory/ProcessPool.lo src/factory/ThreadPool.lo src/reactor/ReactorBase.lo src/reactor/ReactorSelect.lo src/reactor/ReactorPoll.lo src/reactor/ReactorEpoll.lo src/reactor/ReactorKqueue.lo src/pipe/PipeBase.lo src/pipe/PipeEventfd.lo src/pipe/PipeUnsock.lo src/pipe/Channel.lo src/pipe/Msgqueue.lo src/lock/Semaphore.lo src/lock/Mutex.lo src/lock/RWLock.lo src/lock/SpinLock.lo src/lock/FileLock.lo src/lock/AtomicLock.lo src/lock/Cond.lo src/network/Client.lo src/network/Connection.lo src/network/Manager.lo src/network/Port.lo src/network/ReactorAccept.lo src/network/ReactorProcess.lo src/network/ReactorThread.lo src/network/Server.lo src/network/Socket.lo src/network/TaskWorker.lo src/network/Worker.lo src/os/AsyncIO.lo src/os/linux_aio.lo src/os/gcc_aio.lo src/protocol/Base.lo src/protocol/Base64.lo src/protocol/Http.lo src/protocol/Http2.lo src/protocol/Mqtt.lo src/protocol/Nova.lo src/protocol/Sha1.lo src/protocol/SSL.lo src/protocol/WebSocket.lo src/util/Baseoperator.lo src/util/BinaryData.lo src/util/DNS.lo src/util/Module.lo src/util/Sendfile.lo src/util/Signal.lo src/util/Timer.lo thirdparty/php_http_parser.lo thirdparty/multipart_parser.lo -Wl,-rpath,/usr/zan/lib -L/usr/zan/lib -lhiredis_linux -lz -lrt -lssl -lcrypt -lcrypto -lcurl
cc -shared  .libs/swoole.o .libs/swoole_server.o .libs/swoole_server_port.o .libs/swoole_connpool.o .libs/swoole_client.o .libs/swoole_event.o .libs/swoole_timer.o .libs/swoole_async.o .libs/swoole_process.o .libs/swoole_buffer.o .libs/swoole_http_server.o .libs/swoole_http_v2_server.o .libs/swoole_websocket_server.o .libs/swoole_http_client.o .libs/swoole_mysql.o .libs/swoole_redis.o .libs/swoole_nova.o src/.libs/Base.o src/core/.libs/hashmap.o src/core/.libs/RingQueue.o src/core/.libs/string.o src/core/.libs/array.o src/core/.libs/list.o src/core/.libs/heap.o src/core/.libs/log.o src/core/.libs/rbtree.o src/memory/.libs/ShareMemory.o src/memory/.libs/MemoryGlobal.o src/memory/.libs/RingBuffer.o src/memory/.libs/FixedPool.o src/memory/.libs/Malloc.o src/memory/.libs/Table.o src/memory/.libs/Buffer.o src/factory/.libs/Factory.o src/factory/.libs/FactoryThread.o src/factory/.libs/FactoryProcess.o src/factory/.libs/ProcessPool.o src/factory/.libs/ThreadPool.o src/reactor/.libs/ReactorBase.o src/reactor/.libs/ReactorSelect.o src/reactor/.libs/ReactorPoll.o src/reactor/.libs/ReactorEpoll.o src/reactor/.libs/ReactorKqueue.o src/pipe/.libs/PipeBase.o src/pipe/.libs/PipeEventfd.o src/pipe/.libs/PipeUnsock.o src/pipe/.libs/Channel.o src/pipe/.libs/Msgqueue.o src/lock/.libs/Semaphore.o src/lock/.libs/Mutex.o src/lock/.libs/RWLock.o src/lock/.libs/SpinLock.o src/lock/.libs/FileLock.o src/lock/.libs/AtomicLock.o src/lock/.libs/Cond.o src/network/.libs/Client.o src/network/.libs/Connection.o src/network/.libs/Manager.o src/network/.libs/Port.o src/network/.libs/ReactorAccept.o src/network/.libs/ReactorProcess.o src/network/.libs/ReactorThread.o src/network/.libs/Server.o src/network/.libs/Socket.o src/network/.libs/TaskWorker.o src/network/.libs/Worker.o src/os/.libs/AsyncIO.o src/os/.libs/linux_aio.o src/os/.libs/gcc_aio.o src/protocol/.libs/Base.o src/protocol/.libs/Base64.o src/protocol/.libs/Http.o src/protocol/.libs/Http2.o src/protocol/.libs/Mqtt.o src/protocol/.libs/Nova.o src/protocol/.libs/Sha1.o src/protocol/.libs/SSL.o src/protocol/.libs/WebSocket.o src/util/.libs/Baseoperator.o src/util/.libs/BinaryData.o src/util/.libs/DNS.o src/util/.libs/Module.o src/util/.libs/Sendfile.o src/util/.libs/Signal.o src/util/.libs/Timer.o thirdparty/.libs/php_http_parser.o thirdparty/.libs/multipart_parser.o  -lpthread -L/usr/zan/lib -lhiredis_linux -lz -lrt -lssl -lcrypt -lcrypto /usr/lib/i386-linux-gnu/libcurl.so  -pthread -Wl,-rpath -Wl,/usr/zan/lib -Wl,-soname -Wl,zan.so -o .libs/zan.so
/usr/bin/ld: skipping incompatible /usr/zan/lib/libhiredis_linux.a when searching for -lhiredis_linux
/usr/bin/ld: cannot find -lhiredis_linux
collect2: error: ld returned 1 exit status
make: *** [zan.la] 错误 1

**Comment by xiyang2011** [comment]
我尝试了使用make && make install 编辑成功zan.so，但是启动不了zan.so,有如下错误
' service php-fpm restart
Gracefully shutting down php-fpm . done
Starting php-fpm [29-Jun-2017 07:29:40] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php/lib/php/extensions/no-debug-non-zts-20151012/zan.so' - /usr/local/php/lib/php/extensions/no-debug-non-zts-20151012/zan.so: undefined symbol: zval_used_for_init in Unknown on line 0
 done

还有一个问题就是，我尝试了将lib文件夹中哪个mac版本的库改为linux版本，居然可以成功通过make,不过生成的zan.so扩展，也是上面的错误加载不了，以上测试都是使用php7.0.7版 @xhjcehust 

我再重新下载了源码编译了一遍，还是将mac版本的库改为linux版本，这次居然成功了，php加载也成功了！！！！
这个方法也不行，一样报错，是用不了的

**Comment by xiyang2011** [comment]
还有一个问题就是，我尝试了将lib文件夹中哪个mac版本的库改为linux版本，居然可以成功通过make,不过生成的zan.so扩展，也是上面的错误加载不了，以上测试都是使用php7.0.7版
