### ISSUE TITLE
install zan via pecl/yum/apt-get?

### ISSUE THREAD

**Issue by gouchaoer** [youzan/zan#6]
It's inconvenient to compile zan extention in production environment. Of course docker is a selection.
But is zan stable enough to submit to pecl?

**Comment by liues1992** [comment]
Fork a existing pecl package and add it to pecl again?
Never see this happened before.

**Comment by zxcvdavid** [comment]
@gouchaoer We have no plan to publish zan in other repo yet. 
Thanks for your suggest, enjoy!  :)
