### ISSUE TITLE
zan compile problem

### ISSUE THREAD

**Issue by gouchaoer** [youzan/zan#7]
root1@ubuntu:~/Desktop/zanphp/zan/zan-extension$ php -v
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

root1@ubuntu:~/Desktop/zanphp/zan/zan-extension$ php -m | grep sockets
sockets

root1@ubuntu:~/Desktop/zanphp/zan/zan-extension$ make
/bin/bash /home/root1/Desktop/zanphp/zan/zan-extension/libtool --mode=compile cc  -I. -I/home/root1/Desktop/zanphp/zan/zan-extension -DPHP_ATOM_INC -I/home/root1/Desktop/zanphp/zan/zan-extension/include -I/home/root1/Desktop/zanphp/zan/zan-extension/main -I/home/root1/Desktop/zanphp/zan/zan-extension -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/home/root1/Desktop/zanphp/zan/zan-extension/include  -DHAVE_CONFIG_H  -std=gnu99 -Wall -pthread -g -O2 -fbounds-check -fstack-check -fstack-protector -fstack-protector-all -fno-strict-aliasing   -c /home/root1/Desktop/zanphp/zan/zan-extension/swoole.c -o swoole.lo 
libtool: compile:  cc -I. -I/home/root1/Desktop/zanphp/zan/zan-extension -DPHP_ATOM_INC -I/home/root1/Desktop/zanphp/zan/zan-extension/include -I/home/root1/Desktop/zanphp/zan/zan-extension/main -I/home/root1/Desktop/zanphp/zan/zan-extension -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/home/root1/Desktop/zanphp/zan/zan-extension/include -DHAVE_CONFIG_H -std=gnu99 -Wall -pthread -g -O2 -fbounds-check -fstack-check -fstack-protector -fstack-protector-all -fno-strict-aliasing -c /home/root1/Desktop/zanphp/zan/zan-extension/swoole.c  -fPIC -DPIC -o .libs/swoole.o
In file included from /home/root1/Desktop/zanphp/zan/zan-extension/swoole.c:20:0:
/home/root1/Desktop/zanphp/zan/zan-extension/php_swoole.h:140:2: error: #error "Enable sockets support, require sockets extension."
 #error "Enable sockets support, require sockets extension."
  ^
Makefile:194: recipe for target 'swoole.lo' failed
make: *** [swoole.lo] Error 1

**Comment by gouchaoer** [comment]
sockets extentsion is already installed

**Comment by liues1992** [comment]
See this issue https://github.com/swoole/swoole-src/issues/1027
It's stupid to fork swoole and re-opensource it.

**Comment by zxcvdavid** [comment]
Solved?

**Comment by gouchaoer** [comment]
I think I have figured what happened.

`https://github.com/youzan/zan/search?utf8=✓&q=COMPILE_DL_SOCKETS&type=`
`http://grokbase.com/t/php/pecl-dev/1396k4zs68/how-do-i-make-a-dependency-on-the-sockets-extension`
`https://github.com/bwoebi/php-uv/blob/master/php_uv.h`
`https://github.com/php/pecl-event-libevent/blob/master/libevent.c`

As we can see, php-uv check sockets by:
```
#if defined(HAVE_SOCKETS) && !defined(COMPILE_DL_SOCKETS)
```
And zan, php-lib-event check sockets by:
```
#if PHP_VERSION_ID >= 50301 && (HAVE_SOCKETS || defined(COMPILE_DL_SOCKETS))
```

I just changed it into php-uv's method. But i ran into error:
```
/home/root1/Desktop/zanphp/zan/zan-extension/php_swoole.h:457:1: error: unknown type name ‘php_socket’
 php_socket *swoole_convert_to_socket(int sock);

```
The reason is `ext/sockets/php_sockets.h` also checks macro`HAVE_SOCKETS ` too. So I hackedd it and defined this macro:
```
#ifdef SW_SOCKETS
#define HAVE_SOCKETS 1

#if PHP_VERSION_ID >= 50301 && (HAVE_SOCKETS || defined(COMPILE_DL_SOCKETS))

#include "ext/sockets/php_sockets.h"

#define SWOOLE_SOCKETS_SUPPORT

#else

#error "Enable sockets support, require sockets extension."

#endif

#endif
```

make success.
But I don't know why extensions try check lib dependency in compiling(sockets is dynamic linked) time. Maybe my php-dev version is compiled without --enable--sockets flag(but dynamic linked)?

**Comment by bcdevhz** [comment]
若执行make编译时报错Enable sockets support, require sockets extension，请确认PHP版本及sockets扩展正确安装。
    1） 保证PHP版本在5.6以上版本。
    2） sockets扩展被正确安装(HAVE_SOCKETS这个宏定义)，如果没有请重新安装。
    3） 若仍然报错，请按编译扩展的步骤安装sockets,即phpize && ./configure XXX && make && make install。
PHP需要正确加载sockets扩展才会开启HAVE_SOCKETS宏。您这边强行打开，运行时zan引用sockets扩展的函数(相当于引用第三方库)，由于找不到sockets扩展，会提示找不到符号表，所以提前至编译时检查。

**Comment by gouchaoer** [comment]
我这个是ubuntu16.04的默认php70版本，php -m可以看到sockets扩展的，强行打开make出来后问题就解决了

**Comment by guigui0326** [comment]
楼主，同样ubuntu16.04， apt 安装的php7.0版本  php -m 也加载了sockets模块 也提示
error: #error "Enable sockets support, require sockets extension."
 #error "Enable sockets support, require sockets extension."
  ^
Makefile:194: recipe for target 'swoole.lo' failed
make: *** [swoole.lo] Error 1
ERROR: `make' failed
请问怎么解决的？难道只能编译安装才可以？

**Comment by gouchaoer** [comment]
我没有继续跟进基于generator的半协程框架zanphp了，因为基于swoole2.x的swoft的全协程框架没有yield调用栈问题，也更简单，代表未来的方向

**Comment by guigui0326** [comment]
嗯  我是使用pecl install swoole安装swoole的时候出现的这种情况，不过编译安装就可以了。很奇怪
