### ISSUE TITLE
代码建议

### ISSUE THREAD

**Issue by kimkit** [youzan/zan#8]
1. 文件格式统一用`unix`，编码统一用`utf-8`，有些文件是`doc`格式的；
2. 缩进使用空格，移除行尾空白，现在空格和`tab`混用，同一个文件有好几种方式；
3. 删除没有用的文件，例如：`clean`和`clean.sh`重复；
4. `src/core`目录下的文件名改成驼峰方式：

```
array.c          Array.c
hashmap.c        HashMap.c
heap.c           Heap.c
list.c           List.c
log.c            Log.c
rbtree.c         Rbtree.c
string.c         String.c
```

**Comment by kimkit** [comment]
希望`zan`的代码足够整洁，保持代码风格一致。

**Comment by bcdevhz** [comment]
多谢反馈，代码规范在进行中。
