### ISSUE TITLE
undefined symbol: mysqlnd_cset_escape_slashes in Unknown on line 0

### ISSUE THREAD

**Issue by springleng** [youzan/zan#9]
![1](https://user-images.githubusercontent.com/1900972/27625714-1a176796-5c18-11e7-9e8b-7109e0338eae.png)

**Comment by bcdevhz** [comment]
请1）先确认mysqlnd扩展是否安装，2）安装后查看符号表信息，若未定义表明未正确安装。
若安装正确，通过nm命令查找符号表信息，如下：
nm /usr/local/Cellar/php71/7.1.4_16/lib/php/extensions/no-debug-non-zts-20160303/zan.so | grep mysql可查看符号表信息：0000000000029510 T _mysql_escape_slashes
这即表明该函数被编译链进zan.so。

**Comment by springleng** [comment]
使用你的步骤能找到对应的符号表信息，但是make test还是那个warning。
[root@localhost zan-extension]# nm /opt/remi/php71/root/usr/lib64/php/modules/zan.so | grep mysql
00000000002b0840 d arginfo_swoole_mysql_connect
00000000002b07e0 d arginfo_swoole_mysql_escape
00000000002b08a0 d arginfo_swoole_mysql_on
00000000002b06e0 d arginfo_swoole_mysql_prepare
00000000002b0740 d arginfo_swoole_mysql_query
00000000002b07a0 d arginfo_swoole_mysql_setTimeout
0000000000029720 t mysqlclient_args_check
000000000002a320 t mysqlclient_close
0000000000029a80 t mysqlclient_connect
0000000000029890 t mysqlclient_create
0000000000029e40 t mysqlclient_send
0000000000048a40 t mysql_Client_timeout
0000000000048870 t mysql_close
**000000000004dda0 T mysql_escape_slashes**
000000000004deb0 T mysql_handle_quoter
000000000004b0e0 t mysql_handshake
                 **U mysqlnd_cset_escape_slashes**
                 U mysqlnd_find_charset_nr
00000000002b6e88 b mysql_request_buffer
00000000002b6ea0 b swoole_mysql_ce
00000000002b0900 d swoole_mysql_charsets
00000000002ba6d0 B swoole_mysql_class_entry_ptr
000000000004ee80 T swoole_mysql_init
00000000002b04e0 d swoole_mysql_methods
000000000004ac70 t swoole_mysql_onConnect
000000000004d9d0 t swoole_mysql_onError
000000000004b560 t swoole_mysql_onQuery
000000000004b840 t swoole_mysql_onRead
000000000004aee0 t swoole_mysql_onWrite
0000000000049990 t zim_swoole_mysql_begin
00000000000486f0 t zim_swoole_mysql_close
0000000000049570 t zim_swoole_mysql_commit
0000000000049fc0 t zim_swoole_mysql_connect
000000000004da90 t zim_swoole_mysql___construct
000000000004dc20 t zim_swoole_mysql___destruct
0000000000049dc0 t zim_swoole_mysql_escape
0000000000048210 t zim_swoole_mysql_isConnected
000000000004d660 t zim_swoole_mysql_isUsedindex
0000000000048310 t zim_swoole_mysql_on
0000000000048ec0 t zim_swoole_mysql_query
0000000000049150 t zim_swoole_mysql_rollback
000000000004df60 t zim_swoole_mysql_safe_query
000000000004d8b0 t zim_swoole_mysql_setConnectTimeout
000000000004d790 t zim_swoole_mysql_setQueryTimeout
[root@localhost zan-extension]#

**Comment by bcdevhz** [comment]
1. U  mysqlnd_cset_escape_slashes
undefined symbol  表明本模块引用了该符号但未定义，事实上，它依赖于PHP的mysqlnd扩展（您--enable-mysqlnd了当然需要mysqlnd扩展了），正是在mysqlnd扩展定义了该函数(以及您列出的另一个引用但为定义函数mysqlnd_find_charset_nr)。

2.请1）先确认mysqlnd扩展是否安装，2）安装后查看符号表信息，若未定义表明未正确安装。
若PHP已安装mysqlnd，您列出的两个函数应该定义在PHP执行程序中
`nm /opt/php/bin/php | grep mysqlnd_cset_escape_slashes`
0000000000939ec0 T mysqlnd_cset_escape_slashes
` nm /opt/php/bin/php | grep mysqlnd_find_charset_nr`
0000000000939ab6 T mysqlnd_find_charset_nr

3.您这边是不是开启了--enable-mysqlnd的configure选项，想使用mysql的escape特殊字符转义功能。
如果是请按上述步骤确认PHP已正确安装mysqlnd。
若不是想使用转义功能，可忽略这个warning，也可以不用这个configure选项。

**Comment by springleng** [comment]
可以我PHP版本或者安装问题吧，我是yum安装的PHP 7.1.6，mysqlnd也是yum安装的。我自己Mac电脑上没问题。不过从你的解答中学到了东西，非常感谢！
[root@localhost wwwroot]# nm /opt/remi/php71/root/usr/bin/php
nm: /opt/remi/php71/root/usr/bin/php: no symbols
[root@localhost wwwroot]# nm /opt/remi/php71/root/lib64/php/modules/mysqli.so
nm: /opt/remi/php71/root/lib64/php/modules/mysqli.so: no symbols
[root@localhost wwwroot]# nm /opt/remi/php71/root/lib64/php/modules/mysqlnd.so 
nm: /opt/remi/php71/root/lib64/php/modules/mysqlnd.so: no symbols
[root@localhost wwwroot]# nm /opt/remi/php71/root/lib64/php/modules/zan.so | grep mysqlnd
                 U mysqlnd_cset_escape_slashes
                 U mysqlnd_find_charset_nr
[root@localhost wwwroot]#

**Comment by zxcvdavid** [comment]
@springleng 问题解决了吗？如果解决了请close这个issue :)
